-
  name: Playbook tp # name playbook
  hosts:
    - group1 #hosts represente les hosts def dans targets.txt avec l'alias group1

  tasks:
    - name: Test ping
      tag: test_ping
      ping:

-
  name: Create a container for app flask in a docker
  hosts: group1
  become: yes
  roles: # un role un ensemble de tâches, ici on en a definit 2
    - docker
    - container